# Generated by Django 6.0 on 2026-01-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_bookimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='books/images/'),
        ),
    ]
