# Generated by Django 6.0 on 2026-01-04 19:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookimages',
            name='image',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
