# Generated by Django 6.0 on 2026-01-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.IntegerField(max_length=50, unique=True),
        ),
    ]
